-- ============================================================
--  nexacroN-fullstack seed data
--  Loaded after schema.sql by Spring Boot's data.sql auto-run
--  (or by the MVC runner's bootstrap listener).
--
--  Row counts:
--    USERS          3
--    DEPT           7 (2 roots, 5 children across 3 levels)
--    SAMPLE_BOARD   5
--    WIDE_COLUMNS   1
--    FILE_META      2
--    LARGE_DATA     ~1000 rows (generated by loop — see tail)
-- ============================================================

-- ------------------------------------------------------------
-- USERS (3)
-- ------------------------------------------------------------
INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD_HASH, EMAIL, ROLE) VALUES
('admin',  '관리자',   'stub$admin',  'admin@example.com',  'ADMIN'),
('user01', '홍길동',   'stub$user01', 'user01@example.com', 'USER'),
('user02', '김철수',   'stub$user02', 'user02@example.com', 'USER');

-- ------------------------------------------------------------
-- DEPT (2 roots + 5 children)
-- ------------------------------------------------------------
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, SORT_ORDER, LEVEL_NO) VALUES
('D001', '본사',       NULL,   1, 1),
('D002', '지사',       NULL,   2, 1),
('D101', '경영지원팀', 'D001', 1, 2),
('D102', '개발팀',     'D001', 2, 2),
('D201', '서울지사',   'D002', 1, 2),
('D202', '부산지사',   'D002', 2, 2),
('D1021','프론트엔드', 'D102', 1, 3);

-- ------------------------------------------------------------
-- SAMPLE_BOARD (5)
-- ------------------------------------------------------------
INSERT INTO SAMPLE_BOARD (TITLE, CONTENT, AUTHOR_ID, VIEW_COUNT) VALUES
('환영합니다',     '첫 번째 공지입니다.',                 'admin',  100),
('Nexacro N v24', 'packageN layout sample board.',       'admin',   42),
('샘플 게시글 1',  'body body body',                      'user01',  10),
('샘플 게시글 2',  '한글 테스트 / UTF-8 check',           'user01',   7),
('Lorem ipsum',   'dolor sit amet, consectetur...',      'user02',   0);

-- ------------------------------------------------------------
-- WIDE_COLUMNS (1 row with all 50 columns populated)
-- ------------------------------------------------------------
INSERT INTO WIDE_COLUMNS (KEY_ID,
    COL_01, COL_02, COL_03, COL_04, COL_05, COL_06, COL_07, COL_08, COL_09, COL_10,
    COL_11, COL_12, COL_13, COL_14, COL_15, COL_16, COL_17, COL_18, COL_19, COL_20,
    COL_21, COL_22, COL_23, COL_24, COL_25, COL_26, COL_27, COL_28, COL_29, COL_30,
    COL_31, COL_32, COL_33, COL_34, COL_35, COL_36, COL_37, COL_38, COL_39, COL_40,
    COL_41, COL_42, COL_43, COL_44, COL_45, COL_46, COL_47, COL_48, COL_49, COL_50
) VALUES ('WIDE-001',
    's01','s02','s03','s04','s05','s06','s07','s08','s09','s10',
     101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
     1.1,  2.2,  3.3,  4.4,  5.5,  6.6,  7.7,  8.8,  9.9, 10.0,
     DATE '2026-01-01', DATE '2026-02-01', DATE '2026-03-01', DATE '2026-04-01', DATE '2026-05-01',
     TIMESTAMP '2026-01-01 10:00:00', TIMESTAMP '2026-01-02 11:00:00', TIMESTAMP '2026-01-03 12:00:00',
     TIMESTAMP '2026-01-04 13:00:00', TIMESTAMP '2026-01-05 14:00:00',
     TRUE, FALSE, TRUE, FALSE, TRUE,
     'clob 46', 'clob 47', 'clob 48', 'clob 49', 'clob 50'
);

-- ------------------------------------------------------------
-- FILE_META (2 pre-registered records — actual binary not shipped)
-- ------------------------------------------------------------
INSERT INTO FILE_META (FILE_ID, ORIGINAL_NAME, STORED_PATH, CONTENT_TYPE, SIZE_BYTES, UPLOADED_BY) VALUES
('11111111-1111-1111-1111-111111111111', 'sample.pdf',  '/upload/sample.pdf',  'application/pdf',           204800,  'admin'),
('22222222-2222-2222-2222-222222222222', 'report.xlsx', '/upload/report.xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 102400, 'user01');

-- ------------------------------------------------------------
-- LARGE_DATA (1000 rows via procedural loop — HSQL-compatible)
-- ------------------------------------------------------------
-- NOTE: HSQL 2.x does not support PL/pgSQL. We load 1000 rows via a
-- recursive CTE-driven INSERT. This is portable to most modern engines.
INSERT INTO LARGE_DATA (CATEGORY, SEQ_NO, VALUE_1, VALUE_2, VALUE_3)
WITH RECURSIVE GEN(N) AS (
    SELECT 1 FROM (VALUES(0))
    UNION ALL
    SELECT N + 1 FROM GEN WHERE N < 1000
)
SELECT
    CASE MOD(N, 10)
        WHEN 0 THEN 'A' WHEN 1 THEN 'B' WHEN 2 THEN 'C' WHEN 3 THEN 'D' WHEN 4 THEN 'E'
        WHEN 5 THEN 'F' WHEN 6 THEN 'G' WHEN 7 THEN 'H' WHEN 8 THEN 'I' ELSE 'J'
    END                               AS CATEGORY,
    N                                 AS SEQ_NO,
    'value-' || CAST(N AS VARCHAR(10)) AS VALUE_1,
    CAST(N AS DECIMAL(18,4)) * 1.25    AS VALUE_2,
    N * 3                              AS VALUE_3
FROM GEN;
