-- ============================================================
--  nexacroN-fullstack seed schema (HSQL in-memory)
--  Statement separator: ^^ (set in application.yml)
--  Dialect: HyperSQL 2.x (CREATE CACHED TABLE not needed — mem db)
--  Target runners: all 8 (javax + jakarta + webflux)
--
--  Tables (7):
--    1. USERS              — login stub + session demo
--    2. SAMPLE_BOARD       — CRUD demo (N/I/U/D/O _RowType_ exercise)
--    3. DEPT               — parent-child tree (TreeView demo)
--    4. LARGE_DATA         — paging + streaming demo (1000 rows after seed)
--    5. WIDE_COLUMNS       — wide-column load (50 columns)
--    6. FILE_META          — file upload / download metadata
--    7. TB_TEST_DATA_TYPE  — testdata type demo (endpoint #10/#11)
-- ============================================================

DROP TABLE IF EXISTS TB_TEST_DATA_TYPE^^
DROP TABLE IF EXISTS FILE_META^^
DROP TABLE IF EXISTS WIDE_COLUMNS^^
DROP TABLE IF EXISTS LARGE_DATA^^
DROP TABLE IF EXISTS DEPT^^
DROP TABLE IF EXISTS SAMPLE_BOARD^^
DROP TABLE IF EXISTS USERS^^

-- ------------------------------------------------------------
-- 1. USERS
-- ------------------------------------------------------------
CREATE TABLE USERS (
    USER_ID        VARCHAR(32)  NOT NULL PRIMARY KEY,
    USER_NAME      VARCHAR(100) NOT NULL,
    PASSWORD_HASH  VARCHAR(256) NOT NULL,
    EMAIL          VARCHAR(200),
    ROLE           VARCHAR(20)  DEFAULT 'USER' NOT NULL,
    ENABLED        BOOLEAN      DEFAULT TRUE NOT NULL,
    CREATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
)^^

-- ------------------------------------------------------------
-- 2. SAMPLE_BOARD
-- ------------------------------------------------------------
CREATE TABLE SAMPLE_BOARD (
    BOARD_ID       INTEGER      GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    TITLE          VARCHAR(200) NOT NULL,
    CONTENT        CLOB,
    AUTHOR_ID      VARCHAR(32)  NOT NULL,
    VIEW_COUNT     INTEGER      DEFAULT 0 NOT NULL,
    CREATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED        BOOLEAN      DEFAULT FALSE NOT NULL,
    CONSTRAINT FK_BOARD_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(USER_ID)
)^^

CREATE INDEX IDX_BOARD_AUTHOR ON SAMPLE_BOARD(AUTHOR_ID)^^
CREATE INDEX IDX_BOARD_CREATED ON SAMPLE_BOARD(CREATED_AT)^^

-- ------------------------------------------------------------
-- 3. DEPT (tree)
-- ------------------------------------------------------------
CREATE TABLE DEPT (
    DEPT_ID        VARCHAR(20)  NOT NULL PRIMARY KEY,
    DEPT_NAME      VARCHAR(100) NOT NULL,
    PARENT_ID      VARCHAR(20),
    SORT_ORDER     INTEGER      DEFAULT 0 NOT NULL,
    LEVEL_NO       INTEGER      DEFAULT 1 NOT NULL,
    ENABLED        BOOLEAN      DEFAULT TRUE NOT NULL,
    CONSTRAINT FK_DEPT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES DEPT(DEPT_ID)
)^^

CREATE INDEX IDX_DEPT_PARENT ON DEPT(PARENT_ID)^^

-- ------------------------------------------------------------
-- 4. LARGE_DATA (paging + streaming target)
-- ------------------------------------------------------------
CREATE TABLE LARGE_DATA (
    ROW_ID         BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    CATEGORY       VARCHAR(10)  NOT NULL,
    SEQ_NO         INTEGER      NOT NULL,
    VALUE_1        VARCHAR(100),
    VALUE_2        DECIMAL(18,4),
    VALUE_3        INTEGER,
    CREATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
)^^

CREATE INDEX IDX_LARGE_CATEGORY ON LARGE_DATA(CATEGORY)^^
CREATE INDEX IDX_LARGE_SEQ ON LARGE_DATA(SEQ_NO)^^

-- ------------------------------------------------------------
-- 5. WIDE_COLUMNS (50 columns, 1 row demo)
-- ------------------------------------------------------------
CREATE TABLE WIDE_COLUMNS (
    KEY_ID         VARCHAR(20)  NOT NULL PRIMARY KEY,
    COL_01 VARCHAR(50), COL_02 VARCHAR(50), COL_03 VARCHAR(50), COL_04 VARCHAR(50), COL_05 VARCHAR(50),
    COL_06 VARCHAR(50), COL_07 VARCHAR(50), COL_08 VARCHAR(50), COL_09 VARCHAR(50), COL_10 VARCHAR(50),
    COL_11 INTEGER,     COL_12 INTEGER,     COL_13 INTEGER,     COL_14 INTEGER,     COL_15 INTEGER,
    COL_16 INTEGER,     COL_17 INTEGER,     COL_18 INTEGER,     COL_19 INTEGER,     COL_20 INTEGER,
    COL_21 DECIMAL(18,4), COL_22 DECIMAL(18,4), COL_23 DECIMAL(18,4), COL_24 DECIMAL(18,4), COL_25 DECIMAL(18,4),
    COL_26 DECIMAL(18,4), COL_27 DECIMAL(18,4), COL_28 DECIMAL(18,4), COL_29 DECIMAL(18,4), COL_30 DECIMAL(18,4),
    COL_31 DATE,         COL_32 DATE,         COL_33 DATE,         COL_34 DATE,         COL_35 DATE,
    COL_36 TIMESTAMP,    COL_37 TIMESTAMP,    COL_38 TIMESTAMP,    COL_39 TIMESTAMP,    COL_40 TIMESTAMP,
    COL_41 BOOLEAN,      COL_42 BOOLEAN,      COL_43 BOOLEAN,      COL_44 BOOLEAN,      COL_45 BOOLEAN,
    COL_46 CLOB,         COL_47 CLOB,         COL_48 CLOB,         COL_49 CLOB,         COL_50 CLOB
)^^

-- ------------------------------------------------------------
-- 7. TB_TEST_DATA_TYPE — testdata column-type demo
-- (ported from boot-jdk17-jakarta-legacy testDataType_mapper.xml)
-- ------------------------------------------------------------
CREATE TABLE TB_TEST_DATA_TYPE (
    ID              INTEGER      GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    STRING_VALUE    VARCHAR(200),
    INT_VALUE       INTEGER,
    BOOLEAN_VALUE   BOOLEAN,
    LONG_VALUE      BIGINT,
    FLOAT_VALUE     FLOAT,
    DOUBLE_VALUE    DOUBLE,
    BIG_DECIMAL_VALUE DECIMAL(19,4),
    DATE_VALUE      DATE,
    TIME_VALUE      TIMESTAMP,
    DATETIME_VALUE  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    BYTES_VALUE     BLOB
)^^

-- ------------------------------------------------------------
-- 6. FILE_META
-- ------------------------------------------------------------
CREATE TABLE FILE_META (
    FILE_ID        VARCHAR(40)  NOT NULL PRIMARY KEY,
    ORIGINAL_NAME  VARCHAR(255) NOT NULL,
    STORED_PATH    VARCHAR(500) NOT NULL,
    CONTENT_TYPE   VARCHAR(100),
    SIZE_BYTES     BIGINT       NOT NULL,
    UPLOADED_BY    VARCHAR(32),
    UPLOADED_AT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED        BOOLEAN      DEFAULT FALSE NOT NULL,
    CONSTRAINT FK_FILE_UPLOADER FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(USER_ID)
)^^

CREATE INDEX IDX_FILE_UPLOADER ON FILE_META(UPLOADED_BY)^^
CREATE INDEX IDX_FILE_UPLOADED_AT ON FILE_META(UPLOADED_AT)^^
